name: my_checklist
description: A checklist app using BLoC.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.3.6'

dependencies:
  another_flushbar: ^1.12.29
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  hydrated_bloc: ^8.1.0
  path_provider: ^2.0.9

dev_dependencies:
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

assets:
  - assets/icon/my_checklist_icon.png

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/my_checklist_icon.png"
  min_sdk_android: 18 # android min sdk min:16, default 21
